### ISSUE TITLE
Set timer from signal callback warning - needs resolution

### ISSUE THREAD

**Issue by nhed** [nmathewson/libevent-book#12]
In nmathewson/libevent-book/blob/master/Ref4_event.txt under _constructing_signal_events there is a warning about setting timers from signal callback "It might not be supported".

I did a SIMPLE test and did not run into a problem, furthermore it would make sense for this to potentially be a problem in the signal handler itself, rather than the callback.  I assume that the callback should be executing in the event-loop context and thus should be okay.  In either case, IMO this should either go away or become more definitive, i.e. list cases, environments where it is not supported.

Thanks
   -Nevo

**Comment by azat** [comment]
Yes, everything should work, see referenced PR
